version: "2"

services:
    postgres:
        image: postgres
        environment:
            POSTGRES_PASSWORD: jrs123
            POSTGRES_USER: jrs
            POSTGRES_DB: weatherapp
    web:
        build:
            context: .
            dockerfile: Dockerfile
        ports: 
         - "5002-5002"